dcts/radix.meme

package-lock.json, package.json
Blind merging let to invalid syntax pushed to main. This PR fixes this.
=> fix package json conflicts

app/_components/CoinCard.tsx, app/_components/Gallery.tsx, app/page.tsx, app/token/[address]/page.tsx, next.config.mjs, package-lock.json, types/index.ts
add home page gallery 
[Untitled_ Sep 21,2024 10_11 AM.webm](https://github.com/user-attachments/assets/a0f956a5-442d-4f24-b117-b36126847ba9)
-> todo: fetch on chain data
=> add Gallery + CoinCard

app/_components/Navbar.tsx, app/_store/store.ts, app/_store/subscriptions.ts, app/_store/userSlice.ts, app/layout.tsx, package-lock.json, package.json
Added connect button. 
Do not merge, I had to remove exporting metadata.
=> Add connect button

app/_components/CoinCard.tsx, app/_components/Gallery.tsx, app/globals.css, next.config.mjs
I kept the original card and created a card2 in case @SiegfriedBz you need the card you created.
I just wanted to do the layout in a way where the cards start at the baseline and there is flex-wrap to fit as many cols as possilbe. Similar to how dexteronradix.com/team works.
=> make cards more compact

components/CreateCoinForm.tsx, components/Gallery.tsx, components/ui/gallery-with-hover.tsx, components/ui/progress.tsx
=> small fixes

components/CreateCoinForm.tsx, tailwind.config.ts
[Untitled_ Sep 22,2024 2_32 PM.webm](https://github.com/user-attachments/assets/00893aba-bc7d-453f-938e-229a9c0320c5)
=> add effects

app/page.tsx, components/ui/animated-modal.tsx
Added button 'How it works' with this animated modal as suggested by @SiegfriedBz https://ui.aceternity.com/components/animated-modal
=> Add button how it works and modal for it

app/page.tsx, tailwind.config.ts
=> animate 3 coins

app/page.tsx
add shadow on hover + push down effect on click + update colors
[Untitled_ Sep 23,2024 10_26 PM (1).webm](https://github.com/user-attachments/assets/efc6eeb1-bc74-4129-80e7-8ac102b4f318)
=> Update how it works btn

utils/tx-utils.ts
Added a utility file with functions to create basic tx manifests for launching a token, buy tokens and sell tokens.
=> added tx-utils file

app/_actions/createCoinAction.ts, app/_zod/index.ts, components/CreateCoinForm.tsx
transient fix the form + server actions to allow to create TRX
=> transient fix create-coin-form + server-action

components/Card.tsx, components/ui/animated-modal.tsx, tailwind.config.ts
=> change bg-black to bg-dexter-grey-dark

app/page.tsx
fix responsive
- hero height
- hero img colliding with here title
=> fix hero responsive height

app/layout.tsx, app/page.tsx, components/Navbar.tsx
=> fix navbar + hero position

app/token/[address]/page.tsx, components/TokenDetails.tsx, tailwind.config.ts
Added Buy and Sell tabs for the Token Details page
=> Token details

app/_store/tokenSlice.ts, components/TokenDetails.tsx
Added mockdata for buy/sell panel
=> Add mock data

app/layout.tsx, app/page.tsx
=> fix-bottom-cta

app/page.tsx
=> fix bottom CTA design

components/TokenDetails.tsx
Fixed mobile screen for the token details
=> Fix mobile responsiveness

app/layout.tsx, components/CreateCoinForm.tsx, components/Toaster.tsx, package-lock.json, package.json
=> Add toaster

components/CreateCoinForm.tsx
revalidate / path on success create coin => purge cached data 
https://nextjs.org/docs/app/api-reference/functions/revalidatePath
=> revalidate / page after create new coin

app/_store/subscriptions.ts, app/_store/tokenSlice.ts, app/_store/tokenStoreSlice.ts, components/CreateCoinForm.tsx, components/TokenDetails.tsx
- remove deprecated code
- remove console logs
- remove unneeded imports
- disable buy/sell for now until user experience is nice
=> remove unneccessary code and console logs + disabe buy/sell for now

app/token/[address]/page.tsx, components/TokenDetails.tsx
@SiegfriedBz I used your approach to fetch data for the token details server side. 
We can add an improvement to use the `<Suspense>` pattern to show a loading UI to increase speed.
=> server side fetching for tokenDetails page

app/_zod/index.ts, components/CreateCoinForm.tsx, components/TokenDetails.tsx
=> Revert "improve"

app/_zod/index.ts, components/CreateCoinForm.tsx, components/TokenDetails.tsx
=> Revert "Revert "improve""

components/CreateCoinForm.tsx, components/TokenDetails.tsx
=> fix scrolling blocked issue

app/_actions/revalidate-twist.ts, components/CreateCoinForm.tsx
attempt.. to send request to server to enforce cache purge on / page after creating new coin
=> revalidate / after create coin

app/layout.tsx, package-lock.json, package.json
allows to track number / location of visitors and page views
https://vercel.com/docs/analytics/quickstart#add-the-analytics-component-to-your-app
=> add-vercel-analytics

app/token/[address]/page.tsx, components/TokenDetails.tsx, components/TokenDetailsGetDataWrapper.tsx, utils/index.ts
solves #138 
add suspense + skeleton to /token/:address page
[Untitled_ Sep 29,2024 5_25 PM (1).webm](https://github.com/user-attachments/assets/1a220a39-490a-43c5-8ad8-84e8a5a050ed)
=> add-suspense-to-token-details-page

components/TokenDetails.tsx
=> remove ducktape fix

components/CoinCard.tsx
Add last price to the coin cards
=> add lastPrice

components/TokenDetails.tsx, utils/index.ts
Makes shortening strings easier and more adaptable. 
You can set any number of preceeding and ending character count and also adapt the abbreviation join string (default is "...").
=> Improve address shortening

components/CoinCard.tsx, components/TokenDetails.tsx
This is not fully working yet:
- UX of buying selling is bad, nothing updates yet
- Selling has a bug, reported here #162 
Just saving so everyone can play around.
=> Buy sell tx

app/page.tsx, components/Navbar.tsx
=> replace beta with stokenet for clarity

app/page.tsx, components/RadixMemeButton.tsx, tailwind.config.ts
- Fix border on warning button
- add click animation to all buttons
- add font-bold to all buttons types
=> Button improvements

components/TokenDetails.tsx
=> Fix ux bugs

types/index.ts, utils/api-calls.ts
I have added in xrdAmount and maxXrdAmount to TTokenData and changed the api call that fetches the token data to include these fields.
I also changed the progress field of TTokenData to now be based on the xrd amounts rather than the token amounts.
This addresses #161
=> changed progress to be xrd based

utils/index.ts
Replaced apostroph with dot in numbers in Buy/Sell
=> Replace apostroph with dot

README.md, package-lock.json, package.json, utils/index.test.ts, vitest.config.ts
- added vitest dependencies
- initialized a first test file, testing the shortenString helper function.
- added minimal documentation on how to add tests.
=> Testing setup

components/CreateCoinForm.tsx, components/ui/prog-animated-modal.tsx
Fixed data flow, the data is propagated to the success modal by passing the variables as props to the child components (also known as "prop drilling"). We generally want to avoid this pattern, as its hard to maintain, but for now this is fine IMO :)
=> update data flow

app/_zod/index.ts, app/globals.css, app/launch/page.tsx, components/CreateCoinForm.tsx, components/Loading.tsx, components/RadixMemeButton.tsx, tailwind.config.ts
- Updated the design of the "Launch token" page
- Updated validation
=> Redesign of the Launch token page

components/CreateCoinForm.tsx, components/ui/prog-animated-modal.tsx
=> Modal redesign

app/page.tsx, components/ui/animated-modal.tsx
Fixed css of the how it works modal
=> Fix css of the how it works modal
